local A = dofile("F:/Ashen Crown/The Ashen Crown/Repo/tools/aseprite/lib_ashen.lua")
local log, close = A.logger(A.OUT .. "_logs/enemies_v2_1790791673.txt")
local M = dofile("F:/Ashen Crown/The Ashen Crown/Repo/tools/aseprite/enemy_v2.lua")
M.run({"SB05", "SB08", "SB09", "SB10", "SB11"}, log)
close()
