"""World v2 art bake (Winlu Fantasy Overworld, native 48px).

Reads content_src/maps/world2.map (WORLD, WORLD_POST, DEEP, DEEP_POST; generated by wgen.py) and writes
game/assets/ext/maps48/<MAP>.json + chunked ground PNGs + one billboard atlas:
  ground    terrain autotiles, shore-aware water, forests/hills, mountain peaks, ground decals, worn roads drawn
            as smooth brushed ribbons (not cell staircases), plank and stone bridges
  objects   upright landmark sprites for every place (towns, castles, towers, caves, shrines...), signposts at road
            forks and milestones along roads; [sheet, sx, sy, sw, sh, x, y, base, frames, place_id]
The Mode-7 renderer draws the chunks as a ground plane and the objects as billboards.
Usage: python tools/world2/bake.py [WORLD WORLD_POST DEEP DEEP_POST] [--preview]"""
import os, sys, json, random, hashlib, zlib
import numpy as np
from PIL import Image, ImageDraw, ImageFilter

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.environ.get("ASHEN_REPO", os.path.dirname(os.path.dirname(HERE)))
ASSETS = os.environ.get("ASHEN_ASSETS", os.path.join(os.path.dirname(REPO), "Assets"))
W48 = os.path.join(ASSETS, "Winlu Fantasy Overworld")
OUT = os.environ.get("ASHEN_OUT", os.path.join(REPO, "game", "assets", "ext", "maps48"))
MAPFILE = os.environ.get("ASHEN_WORLD2", os.path.join(REPO, "content_src", "maps", "world2.map"))
sys.path.insert(0, HERE)
import wgen

T = 48
Q = 24
CHUNK = 2112


def _img(sub, name):
    return Image.open(os.path.join(W48, sub, name)).convert("RGBA")


A1 = _img("tilesets", "Fantasy_World_A1.png")
A2 = _img("tilesets", "Fantasy_World_A2.png")
SHEETS = {"B": _img("tilesets", "Fantasy_World_Buildings.png"), "V": _img("tilesets", "Fantasy_World_vegetation.png"),
          "M": _img("tilesets", "Fantasy_World_Mountains.png"), "T": _img("characters", "!Overworld_towers.png"),
          "D": _img("characters", "!Overworld_decoration.png"), "G": _img("tilesets", "Fantasy_World_B.png")}

GROUND = {"plains": (A2, 0, 0), "dirt": (A2, 2, 0), "grass2": (A2, 12, 0), "red": (A2, 4, 0), "sand": (A2, 0, 3),
          "olive": (A2, 4, 3), "tufts": (A2, 12, 3), "rocky": (A2, 0, 6), "cobble": (A2, 2, 6), "dark": (A2, 4, 6),
          "dark_magic": (A2, 6, 6), "snow": (A2, 0, 9), "salt": (A2, 2, 9), "ash": (A2, 4, 9), "grey": (A2, 6, 9),
          "purple": (A2, 10, 9), "swamp_pool": (A2, 10, 6), "rocky_deep": (A2, 0, 6)}
OVER = {"forest": (A2, 8, 0), "forest_autumn": (A2, 10, 0), "forest_swamp": (A2, 8, 3), "forest_mush": (A2, 10, 3),
        "forest_magic": (A2, 8, 6), "forest_snow": (A2, 8, 9), "hills_desert": (A2, 14, 3), "hills_green": (A2, 12, 9),
        "hills_moss": (A2, 12, 6), "hills_brown": (A2, 14, 6), "hills_snow": (A2, 14, 9)}
LIQUID = {"sea_sand": (A1, 0, 0), "sea_rock": (A1, 8, 0), "deep": (A1, 0, 3), "sea_snow": (A1, 0, 9),
          "lava": (A1, 8, 3), "lava2": (A1, 8, 6), "ice_sea": (A1, 0, 6)}

# ---------------------------------------------------------------- autotiles
_qcache = {}


def quarters(block, n, s, w, e, nw, ne, sw, se):
    key = (id(block[0]), block[1], block[2], n, s, w, e, nw, ne, sw, se)
    t = _qcache.get(key)
    if t is not None:
        return t
    img, bc, br = block
    bx, by = bc * T, br * T
    out = Image.new("RGBA", (T, T), (0, 0, 0, 0))
    for (qx, qy) in ((0, 0), (1, 0), (0, 1), (1, 1)):
        v = n if qy == 0 else s
        h = w if qx == 0 else e
        d = (nw if qx == 0 else ne) if qy == 0 else (sw if qx == 0 else se)
        if v and h and d:
            sx, sy = 2 - qx, 4 - qy
        elif v and h:
            sx, sy = 2 + qx, qy
        elif v:
            sx, sy = (0 if qx == 0 else 3), 4 - qy
        elif h:
            sx, sy = 2 - qx, (2 if qy == 0 else 5)
        else:
            sx, sy = (0 if qx == 0 else 3), (2 if qy == 0 else 5)
        out.alpha_composite(img.crop((bx + sx * Q, by + sy * Q, bx + sx * Q + Q, by + sy * Q + Q)), (qx * Q, qy * Q))
    _qcache[key] = out
    return out


def autolayer(canvas, cells, W, H, group):
    """cells {(x, y): block}; group(x, y) -> hashable; neighbours join when equal (off-map joins)."""
    for (x, y), blk in cells.items():
        g = group(x, y)

        def same(xx, yy):
            return not (0 <= xx < W and 0 <= yy < H) or group(xx, yy) == g
        t = quarters(blk, same(x, y - 1), same(x, y + 1), same(x - 1, y), same(x + 1, y), same(x - 1, y - 1),
                     same(x + 1, y - 1), same(x - 1, y + 1), same(x + 1, y + 1))
        canvas.alpha_composite(t, (x * T, y * T))


def interior(block):
    return quarters(block, *([True] * 8))


def tiled(tile, w, h):
    im = Image.new("RGBA", (w, h))
    for y in range(0, h, tile.height):
        for x in range(0, w, tile.width):
            im.paste(tile, (x, y))
    return im


# ---------------------------------------------------------------- map parsing
def sections():
    out = {}
    cur = None
    for ln in open(MAPFILE, encoding="utf-8"):
        ln = ln.rstrip("\n")
        if ln.startswith("=== "):
            cur = {"id": ln[4:].strip(), "legend": {}, "grid": [], "ents": [], "mode": "hdr"}
            out[cur["id"]] = cur
            continue
        if cur is None:
            continue
        s = ln.strip()
        if cur["mode"] == "hdr":
            if s.startswith("legend:"):
                for p in s[7:].split():
                    k, v = p.split("=", 1)
                    cur["legend"][k] = v
            elif s == "grid:":
                cur["mode"] = "grid"
        elif cur["mode"] == "grid":
            if s.startswith("entities:"):
                cur["mode"] = "ent"
            elif s:
                cur["grid"].append([cur["legend"].get(c, "water") for c in s])
        elif s and not s.startswith("#"):
            cur["ents"].append(s.split())
    return out


# ---------------------------------------------------------------- landmark sprites
# (sheet, col, row, cols, rows[, frames]) in 48px cells; frames step one sprite-width to the right
S = {
    "town_a": ("B", 3, 0, 2, 2), "town_b": ("B", 1, 0, 2, 2), "city_walled": ("B", 2, 5, 2, 2),
    "vil_a": ("B", 1, 2, 2, 1), "vil_b": ("B", 3, 3, 1, 1), "vil_c": ("B", 6, 4, 1, 1), "vil_d": ("B", 4, 5, 1, 1),
    "vil_e": ("B", 3, 5, 1, 1), "hall_grey": ("B", 4, 6, 1, 1), "vil_dark": ("B", 5, 3, 2, 1),
    "vil_snow_a": ("B", 5, 5, 1, 1), "vil_snow_b": ("B", 5, 2, 2, 1), "vil_snow_c": ("B", 4, 7, 1, 1),
    "igloos": ("B", 10, 12, 1, 2), "huts": ("B", 10, 14, 1, 2),
    "desert_a": ("B", 0, 9, 1, 1), "desert_b": ("B", 1, 9, 1, 1), "desert_c": ("B", 0, 10, 2, 1), "desert_d": ("B", 2, 10, 2, 2),
    "palm_vil": ("B", 4, 9, 2, 1), "pagoda": ("B", 3, 15, 1, 1), "pagoda_w": ("B", 4, 15, 1, 1),
    "cath_dark": ("B", 7, 2, 1, 2), "cath_blue": ("B", 7, 4, 1, 2), "palace_ice": ("B", 7, 7, 1, 2),
    "chapel": ("B", 6, 5, 1, 1), "chapel_ice": ("B", 6, 6, 1, 1), "hall": ("B", 6, 7, 1, 1),
    "temple": ("B", 6, 8, 1, 2), "ziggurat": ("B", 7, 9, 1, 1), "mausoleum": ("B", 7, 11, 1, 1), "shrine_red": ("B", 6, 11, 1, 1),
    "keep_dark": ("B", 8, 9, 1, 2), "castle_ice": ("B", 7, 12, 1, 2), "spire_dark": ("B", 6, 12, 1, 4),
    "hall_dark": ("B", 5, 15, 1, 1), "fort_wood": ("B", 5, 6, 1, 2), "tents": ("B", 1, 5, 1, 1), "tents_b": ("B", 0, 5, 1, 1),
    "graves": ("B", 7, 6, 1, 1), "columns": ("B", 6, 10, 2, 1), "statue": ("B", 2, 14, 1, 1), "pyramid": ("B", 4, 11, 2, 2),
    "dig": ("B", 0, 12, 1, 1), "quarry": ("B", 0, 15, 2, 1), "sign": ("B", 5, 0, 1, 1), "sign_b": ("B", 5, 1, 1, 1),
    "lamp": ("B", 0, 3, 1, 1), "dock": ("B", 6, 0, 1, 1), "wallgate": ("B", 8, 7, 1, 1), "rock_gate": ("B", 14, 14, 1, 2),
    "tw_stone": ("T", 2, 0, 1, 2), "tw_grey": ("T", 3, 0, 1, 2), "tw_blue": ("T", 4, 0, 1, 2), "tw_red": ("T", 5, 0, 1, 2),
    "tw_ice": ("T", 6, 0, 1, 2), "tw_sand": ("T", 9, 0, 1, 2), "tw_sand_b": ("T", 10, 0, 1, 2), "tw_sand_ruin": ("T", 11, 0, 1, 2),
    "tw_big": ("T", 1, 0, 1, 2), "tw_ruin": ("T", 1, 2, 1, 2), "tw_ruin_b": ("T", 6, 2, 1, 2), "tw_hood": ("T", 3, 2, 1, 2),
    "tw_moss": ("T", 5, 2, 1, 2), "tw_eye": ("T", 7, 2, 1, 2), "tw_icepeak": ("T", 8, 2, 1, 2), "tw_horn": ("T", 0, 5, 1, 1),
    "tw_frost": ("T", 2, 5, 1, 1), "tw_bone": ("T", 0, 7, 1, 1), "tw_fire": ("T", 9, 5, 1, 1, 3), "tw_fire_b": ("T", 9, 9, 1, 1, 3),
    "cave": ("V", 8, 3, 1, 1), "cave_b": ("V", 8, 2, 1, 1), "cave_c": ("V", 8, 4, 1, 1), "cave_d": ("V", 10, 5, 1, 1),
    "cave_snow": ("V", 11, 5, 1, 1), "cave_bone": ("V", 10, 3, 1, 1), "mine": ("V", 9, 6, 1, 1), "cave_moss": ("V", 6, 9, 1, 1),
    "mt_cave": ("M", 8, 1, 1, 1), "stones": ("V", 9, 0, 1, 1), "stones_ice": ("V", 15, 1, 1, 1), "wreck": ("V", 11, 0, 1, 1),
    "skeleton": ("V", 8, 6, 1, 2), "ribs": ("V", 9, 7, 1, 1), "crystal_b": ("V", 12, 7, 1, 1), "crystal_p": ("V", 11, 7, 1, 1),
    "crystal_o": ("V", 10, 7, 1, 1), "pond": ("V", 1, 5, 1, 1), "willows": ("V", 3, 6, 1, 2), "grove": ("V", 1, 0, 1, 1),
    "banners": ("V", 13, 5, 1, 1), "battlefield": ("V", 12, 6, 1, 1), "mushrooms": ("V", 4, 12, 1, 1),
    "spider": ("M", 8, 11, 2, 2), "spires": ("M", 10, 10, 2, 2), "horn_rock": ("M", 8, 9, 2, 2), "pillars": ("M", 12, 10, 1, 2),
    "mesa": ("M", 14, 10, 2, 1), "rock_grey": ("M", 14, 12, 2, 2),
    "waterfall": ("D", 0, 1, 1, 1, 3), "whirl": ("D", 0, 2, 1, 1, 3), "maw": ("D", 3, 1, 1, 1, 3),
    "obelisk": ("D", 6, 3, 1, 1), "obelisk_glow": ("D", 6, 5, 1, 1, 3), "portal": ("D", 6, 7, 1, 1),
    "portal_fire": ("D", 6, 9, 1, 1, 3), "smoke_city": ("D", 6, 10, 1, 2, 3), "smoke_snow": ("D", 9, 10, 1, 2, 3),
    "tornado": ("D", 6, 0, 1, 2, 3),
    "c_village": ("C", "!$Overworld_Village1.png"), "c_castle1": ("C", "!$Overworld_Castle1.png"),
    "c_castle_desert": ("C", "!$Overworld_Castle1_desert.png"), "c_castle2": ("C", "!$Overworld_Castle2.png"),
    "c_castle3": ("C", "!$Overworld_Castle3.png"), "c_castle_mt": ("C", "!$Overworld_Castle_Mountain.png"),
    "c_castle_magic": ("C", "!$Overworld_Castle_magic.png"), "c_mt1": ("C", "!$Overworld_Mountain1.png"),
    "c_mt2": ("C", "!$Overworld_Mountain2.png"), "c_bigtree": ("C", "!$Overworld_BigTree.png"),
    "c_worldtree": ("C", "!$Overworld_Worldtree.png"), "c_shield": ("C", "!$Overworld_magicshield.png"),
    "c_port": ("C", "!$Overworld_village_sea.png"),
}

# fixed sprites for the story places (existing towns and dungeons keep their look)
FIXED = {
    "L_T01": "c_village", "L_T02": "c_castle1", "L_T03": "c_castle3", "L_T04": "c_port", "L_T05": "c_castle2",
    "L_T06": "c_castle_desert", "L_T07": "c_port", "L_D01": "c_mt2", "L_D03": "c_bigtree", "L_D04": "tw_stone",
    "L_D05": "tw_grey", "L_D06": "tw_ice", "L_D07": "c_castle2", "L_D08": "c_castle_magic", "L_D09": "tw_big",
    "L_D10": "c_shield", "L_D11": "tw_eye", "L_D12": "tw_blue",
}
# kind -> variants; a region-specific list wins ("kind@R09")
KIND = {
    "village": ["vil_a", "vil_b", "vil_c", "vil_d", "vil_e"], "village@R09": ["vil_snow_a", "vil_snow_b", "vil_snow_c", "igloos"],
    "village@R06": ["palm_vil", "desert_a", "desert_b"], "village@R05": ["desert_a", "desert_b", "tents"],
    "village@R02": ["vil_dark", "hall_grey"], "village@R07": ["pagoda", "pagoda_w"], "village@R08": ["vil_c", "huts"],
    "village@U1": ["huts", "tents"], "village@U2": ["hall_grey", "columns"], "village@U3": ["graves", "hall_dark"],
    "town": ["town_a", "town_b"], "city": ["city_walled"], "town_ash": ["vil_dark", "hall_grey"], "town_cliff": ["c_castle_mt"],
    "town_desert": ["desert_d", "desert_c"], "port": ["c_port"], "fort": ["fort_wood", "keep_dark"], "castle": ["c_castle2"],
    "castle_magic": ["c_castle_magic"], "castle_red": ["keep_dark"], "castle_ice": ["castle_ice"], "cathedral": ["cath_dark", "cath_blue"],
    "chapel": ["chapel", "chapel_ice"], "shrine": ["obelisk_glow", "statue", "shrine_red"], "grove": ["willows", "grove"],
    "bigtree": ["c_worldtree", "c_bigtree"], "sky": ["portal", "tw_icepeak"], "milestone": ["lamp"], "crystal": ["crystal_b", "crystal_p", "crystal_o"],
    "dock": ["dock"], "rail": ["wallgate"], "barrow": ["graves", "mausoleum"], "gibbet": ["banners", "battlefield"],
    "crypt": ["mausoleum"], "tomb": ["pyramid", "mausoleum"], "bones": ["skeleton", "ribs"], "crater": ["dig"], "pit": ["quarry"],
    "mine": ["mine"], "cave": ["cave", "cave_b", "cave_c", "cave_d", "mt_cave"], "cave@R09": ["cave_snow"], "cave@U1": ["cave_d", "mine"],
    "chasm": ["cave_bone"], "breach": ["cave_bone"], "dam": ["wallgate"], "gate": ["wallgate", "rock_gate"], "gate_builder": ["portal"],
    "gate_abyss": ["portal_fire"], "lighthouse": ["tw_fire", "tw_fire_b"], "lake": ["whirl"], "city_dark": ["spire_dark"],
    "city_dead": ["hall_dark"], "relay": ["obelisk_glow"], "tower": ["tw_stone", "tw_grey", "tw_blue", "tw_red", "tw_hood", "tw_moss"],
    "tower@R05": ["tw_sand", "tw_sand_b"], "tower@R06": ["tw_sand", "tw_sand_ruin"], "tower@R09": ["tw_ice", "tw_frost"],
    "tower@U3": ["tw_bone", "tw_horn"], "tower_builder": ["tw_eye"], "tower_ice": ["tw_ice"], "city_delver": ["huts"],
    "city_builder": ["smoke_city"], "factory": ["smoke_city"], "archive": ["temple"], "road": ["sign"], "vault": ["ziggurat"],
    "bridge": ["sign_b"], "palace": ["cath_dark"], "choir": ["tw_horn"], "heart": ["maw"], "throat": ["maw"], "camp": ["tents"],
    "ruin": ["columns", "tw_ruin"], "destroyed": ["tw_ruin_b", "tw_ruin"],
}


class Atlas:
    """All billboard sprites packed into one sheet (frames side by side)."""

    def __init__(self):
        self.items = {}
        self.imgs = []

    def get(self, name):
        if name in self.items:
            return self.items[name]
        spec = S[name]
        if spec[0] == "C":
            sh = _img("characters", spec[1])
            fw, fh = sh.width // 3, sh.height // 4
            frames = [sh.crop((fw, 0, 2 * fw, fh))]
        else:
            sh = SHEETS[spec[0]]
            c, r, cw, ch = spec[1:5]
            nf = spec[5] if len(spec) > 5 else 1
            frames = [sh.crop(((c + i * cw) * T, r * T, (c + i * cw + cw) * T, (r + ch) * T)) for i in range(nf)]
        bb = None
        for f in frames:
            b = f.getbbox()
            if b:
                bb = b if bb is None else (min(bb[0], b[0]), min(bb[1], b[1]), max(bb[2], b[2]), max(bb[3], b[3]))
        if bb is None:
            bb = (0, 0, 1, 1)
        frames = [f.crop(bb) for f in frames]
        self.imgs.append((name, frames))
        self.items[name] = None
        return name

    def pack(self):
        """-> atlas image, {name: (sx, sy, sw, sh, frames)}"""
        rows, x, y, rowh, width = {}, 0, 0, 0, 1024
        pos = {}
        for name, frames in self.imgs:
            w, h = frames[0].width * len(frames), frames[0].height
            if x + w > width:
                x, y, rowh = 0, y + rowh + 2, 0
            pos[name] = (x, y, frames[0].width, h, len(frames))
            x += w + 2
            rowh = max(rowh, h)
        im = Image.new("RGBA", (width, y + rowh + 2), (0, 0, 0, 0))
        for name, frames in self.imgs:
            sx, sy, sw, sh, n = pos[name]
            for i, f in enumerate(frames):
                im.paste(f, (sx + i * sw, sy))
        return im, pos


def pick(options, key):
    h = int(hashlib.md5(key.encode()).hexdigest()[:8], 16)
    return options[h % len(options)]


# ---------------------------------------------------------------- bake
SEA = ("water", "deep")
FOREST_BY_BASE = {"plains": "forest", "grass2": "forest_autumn", "olive": "forest_magic", "sand": "forest_swamp",
                  "snow": "forest_snow", "salt": "forest", "ash": "forest_autumn", "rocky": "forest_snow", "swamp": "forest_swamp"}
HILLS_BY_BASE = {"plains": "hills_green", "grass2": "hills_moss", "olive": "hills_moss", "sand": "hills_desert", "salt": "hills_desert",
                 "snow": "hills_snow", "ash": "hills_brown", "rocky": "hills_brown", "swamp": "hills_moss"}
PEAKS = {"green": [(0, 0), (2, 0), (4, 0), (0, 2), (2, 2), (4, 2)], "brown": [(0, 4), (2, 4), (4, 4)],
         "snow": [(6, 0), (6, 4)], "grey": [(10, 12), (12, 12), (10, 14)], "ice": [(12, 14)]}
PEAK_BY_BASE = {"plains": "green", "grass2": "green", "olive": "green", "swamp": "green", "sand": "brown", "salt": "brown",
                "ash": "brown", "rocky": "grey", "snow": "snow", "cave_floor": "brown", "ruin_floor": "grey", "bone": "grey",
                "crystal_floor": "grey"}
GROUND_OF = {"plains": "plains", "grass2": "grass2", "sand": "sand", "salt": "salt", "snow": "snow", "ash": "ash", "olive": "olive",
             "rocky": "rocky", "swamp": "olive", "cave_floor": "rocky_deep", "ruin_floor": "grey", "bone": "purple",
             "crystal_floor": "dark_magic", "road": "rocky", "path": "plains", "ice": "snow"}
BASEK = set(GROUND_OF) - {"road", "path", "ice"}
DECALS = {   # ground kind -> [(sheet, col, row), ...], density
    "plains": ([("V", 1, 3), ("V", 0, 4), ("V", 1, 4), ("V", 8, 8), ("V", 9, 9), ("V", 8, 0), ("V", 1, 1)], 0.05),
    "grass2": ([("V", 13, 8), ("V", 14, 8), ("V", 8, 8), ("V", 9, 4)], 0.05),
    "sand": ([("V", 6, 13), ("V", 7, 13), ("V", 6, 14), ("V", 13, 7), ("V", 14, 7), ("V", 9, 5)], 0.05),
    "salt": ([("V", 9, 5), ("V", 11, 3), ("V", 14, 7)], 0.03),
    "snow": ([("V", 14, 1), ("V", 14, 2), ("V", 15, 3), ("V", 1, 11)], 0.04),
    "ash": ([("V", 0, 8), ("V", 0, 9), ("V", 1, 8), ("V", 9, 4), ("V", 11, 3), ("V", 12, 12)], 0.06),
    "olive": ([("V", 0, 12), ("V", 1, 12), ("V", 2, 12), ("V", 9, 11), ("V", 8, 9)], 0.05),
    "swamp": ([("V", 7, 9), ("V", 0, 12), ("V", 5, 4)], 0.06),
    "rocky": ([("V", 8, 1), ("V", 11, 2), ("V", 9, 4), ("V", 10, 4)], 0.05),
    "cave_floor": ([("V", 11, 3), ("V", 9, 5), ("V", 8, 1), ("V", 10, 8)], 0.05),
    "ruin_floor": ([("V", 11, 2), ("V", 8, 1), ("B", 6, 10)], 0.03),
    "bone": ([("V", 9, 7), ("V", 12, 6), ("V", 13, 6), ("V", 14, 6)], 0.05),
    "crystal_floor": ([("V", 10, 8), ("V", 11, 8), ("V", 12, 8)], 0.07),
}


def bake(sec, post, deep):
    mid = sec["id"]
    grid = sec["grid"]
    H, W = len(grid), max(len(r) for r in grid)
    for r in grid:
        while len(r) < W:
            r.append("water")
    rng = random.Random(zlib.crc32(mid.encode()))
    k = lambda x, y: grid[y][x] if 0 <= x < W and 0 <= y < H else ("wall_rock" if deep else "deep")
    noise = wgen.value_noise(H, W, 5, 77 + len(mid))
    noise2 = wgen.value_noise(H, W, 3, 91 + len(mid))

    # ground under every cell: own kind, or the most common base kind nearby (for forest/hills/mountain/road...)
    def base_of(x, y):
        kk = grid[y][x]
        if kk in BASEK:
            return kk
        cnt = {}
        for r in (1, 2, 3, 5):
            for dy in range(-r, r + 1):
                for dx in range(-r, r + 1):
                    v = k(x + dx, y + dy)
                    if v in BASEK:
                        cnt[v] = cnt.get(v, 0) + 1
            if cnt:
                return max(cnt, key=cnt.get)
        return "cave_floor" if deep else "plains"
    base0 = [[base_of(x, y) for x in range(W)] for y in range(H)]
    # region edges drawn ragged: the look of the ground is taken from a noise-displaced cell (gameplay keeps the grid)
    ox = (wgen.fbm(H, W, 301 + len(mid), cells=(16, 8, 4)) - 0.5) * 18
    oy = (wgen.fbm(H, W, 419 + len(mid), cells=(16, 8, 4)) - 0.5) * 18
    base = [[base0[min(H - 1, max(0, y + int(round(oy[y, x]))))][min(W - 1, max(0, x + int(round(ox[y, x]))))]
             for x in range(W)] for y in range(H)]
    for y in range(H):
        for x in range(W):
            if base0[y][x] in ("snow",) and grid[y][x] in ("forest", "mountain", "hills"):
                base[y][x] = base0[y][x]
    bg = (10, 8, 12, 255) if deep else (24, 44, 92, 255)
    cv = Image.new("RGBA", (W * T, H * T), bg)

    # 1) ground everywhere (under water too, so smooth shorelines have land beneath), each kind a blended autotile
    first = "dark" if deep else "plains"
    autolayer(cv, {(x, y): GROUND[first] for y in range(H) for x in range(W)}, W, H, lambda x, y: True)
    kinds = sorted({GROUND_OF.get(base[y][x], "plains") for y in range(H) for x in range(W)} - {first})
    for i, gk in enumerate(kinds):
        m = np.array([[GROUND_OF.get(base[y][x]) == gk for x in range(W)] for y in range(H)])
        soft_fill(cv, m, interior(GROUND[gk]), W, H, 700 + i, tint=TINT.get(gk))
    if deep:
        # solid rock: dark basalt mass (the rim near open floor gets peaks later)
        rock = np.array([[grid[y][x] == "wall_rock" for x in range(W)] for y in range(H)])
        soft_fill(cv, rock, interior(GROUND["dark"]), W, H, 650, tint=(0.34, 0.28, 0.27))
    # 2) liquids as smooth bodies: blurred cell masks, foam and shallows at the edge (collision keeps the cells)
    cells_of = lambda ks: np.array([[grid[y][x] in ks for x in range(W)] for y in range(H)])
    wet = cells_of(("water", "deep", "bridge"))
    if wet.any():
        liquid(cv, wet, interior(LIQUID["sea_rock" if deep else "sea_sand"]), W, H, 11 + len(mid),
               foam=(214, 236, 236) if not deep else (120, 150, 160), shallow=1.14 if not deep else 1.0,
               bank=0.80, deep_mask=cells_of(("deep",)), deep_tile=interior(LIQUID["deep"]))
    lv = cells_of(("lava",))
    if lv.any():
        liquid(cv, lv, interior(LIQUID["lava"]), W, H, 29, foam=(255, 226, 120), shallow=1.0, bank=0.45)
    # swamp pools and tufts, ice sheets
    sw = {(x, y): GROUND["swamp_pool"] for y in range(H) for x in range(W) if grid[y][x] == "swamp" and noise2[y, x] > 0.45}
    autolayer(cv, sw, W, H, lambda x, y: (x, y) in sw)
    ice = {(x, y): GROUND["snow"] for y in range(H) for x in range(W) if grid[y][x] == "ice"}
    autolayer(cv, ice, W, H, lambda x, y: k(x, y) == "ice")
    # 3) ground decals (flat, baked)
    for y in range(H):
        for x in range(W):
            kk = grid[y][x]
            d = DECALS.get(kk if kk != "swamp" else "swamp")
            if not d or rng.random() > d[1]:
                continue
            sh, c, r = rng.choice(d[0])
            spr = SHEETS[sh].crop((c * T, r * T, c * T + T, r * T + T))
            cv.alpha_composite(spr, (x * T + rng.randint(-8, 8), y * T + rng.randint(-8, 8)) if 0 < x < W - 1 and 0 < y < H - 1 else (x * T, y * T))
    # 3b) farmland around villages and towns, wrecks off the coasts
    places, _ = places_for(mid)
    wheat = [SHEETS["B"].crop((4 * T, 3 * T, 5 * T, 4 * T)), SHEETS["B"].crop((4 * T, 4 * T, 5 * T, 5 * T))]
    occupied = {(v[0], v[1]) for v in places.values()}
    for pid, (px, py, kind, reg) in sorted(places.items()):
        if kind not in ("village", "town", "city", "fort", "town_cliff") or deep or reg in ("R09",):
            continue
        # one or two tilled plots (2x2 or 3x2 cells) beside the settlement, on open plains only
        plots = 0
        for (dx, dy) in sorted(((2, 1), (-4, 1), (1, 2), (-3, -3), (2, -3), (-2, 2)), key=lambda d: rng.random()):
            if plots >= (2 if kind in ("town", "city") else 1):
                break
            pw = rng.choice((2, 3))
            cells_p = [(px + dx + i, py + dy + j) for i in range(pw) for j in range(2)]
            if all(0 <= x < W and 0 <= y < H and grid[y][x] in ("plains", "grass2", "olive") and (x, y) not in occupied
                   for x, y in cells_p):
                for i, (x, y) in enumerate(cells_p):
                    cv.alpha_composite(wheat[(y - py - dy) % 2], (x * T, y * T))
                occupied.update(cells_p)
                plots += 1
    if not deep:
        wrecks = [SHEETS["V"].crop((10 * T, 0, 11 * T, T)), SHEETS["V"].crop((10 * T, 2 * T, 11 * T, 3 * T))]
        for y in range(1, H - 1):
            for x in range(1, W - 1):
                if grid[y][x] == "water" and rng.random() < 0.004 and all(grid[y + dy][x + dx] in SEA for dx in (-1, 0, 1) for dy in (-1, 0, 1)):
                    cv.alpha_composite(rng.choice(wrecks), (x * T, y * T))
    # 4) roads: smooth worn ribbons over the cells (collision is unchanged: the cells stay road/path)
    roads(cv, grid, W, H, deep)
    # 5) hills and forests: one look per connected patch (majority ground under it)
    cb = comp_major(grid, base0, W, H, ("hills", "forest", "mountain", "wall_rock"))
    hills = {(x, y): OVER[HILLS_BY_BASE.get(cb[(x, y)], "hills_green")] for y in range(H) for x in range(W) if grid[y][x] == "hills"}
    autolayer(cv, hills, W, H, lambda x, y: k(x, y) == "hills")
    fo = {}
    for y in range(H):
        for x in range(W):
            if grid[y][x] == "forest":
                fo[(x, y)] = OVER[FOREST_BY_BASE.get(cb[(x, y)], "forest")]
    autolayer(cv, fo, W, H, lambda x, y: k(x, y) == "forest")
    # 6) mountains / cave rock
    mountains(cv, grid, cb, W, H, deep, rng)
    if mid == "WORLD_POST":
        grade_ruin(cv, W, H)
    return cv, W, H


def grade_ruin(cv, W, H):
    """World of Ruin: drained, rust-and-ash colours (billboards keep their own colours)."""
    def fn(reg, ups, y0):
        rgb = reg[..., :3]
        lum = (rgb[..., 0] * 0.3 + rgb[..., 1] * 0.59 + rgb[..., 2] * 0.11)[..., None]
        rgb[:] = (rgb * 0.62 + lum * 0.38) * np.array([1.0, 0.92, 0.82], dtype=np.float32) * 0.88
        return reg
    strips(cv, W, H, [], fn)


SC = 4                     # low-res masks: 12 px per cell
LOW = T // SC


def cell_low(mask, W, H):
    return np.kron(mask.astype(np.float32), np.ones((LOW, LOW), dtype=np.float32))


def blur_low(arr, sigma):
    im = Image.fromarray((np.clip(arr, 0, 1) * 255).astype(np.uint8), "L").filter(ImageFilter.GaussianBlur(sigma))
    return np.asarray(im, dtype=np.float32) / 255.0


def smooth_noise(H, W, seed, cell_px=10):
    """noise in [-0.5, 0.5] at low res (LOW px per map cell), feature size ~cell_px full-res pixels"""
    g = np.random.default_rng(seed).random((H * T // cell_px + 2, W * T // cell_px + 2)).astype(np.float32)
    im = Image.fromarray(g, "F").resize((W * LOW, H * LOW), Image.BILINEAR)
    return np.asarray(im, dtype=np.float32) - 0.5


def strips(cv, W, H, lows, fn, rows=11):
    """Run fn(region_rgba_float, [full-res arrays of each low map], y0) over horizontal strips (memory-bounded)."""
    for cy in range(0, H, rows):
        y0, y1 = cy * T, min(H, cy + rows) * T
        l0, l1 = max(0, cy * LOW - 2), min(H * LOW, (cy + rows) * LOW + 2)
        ups = []
        for lw in lows:
            im = Image.fromarray(lw[l0:l1], "F").resize((W * T, (l1 - l0) * SC), Image.BILINEAR)
            a = np.asarray(im, dtype=np.float32)
            ups.append(a[(y0 - l0 * SC):(y1 - l0 * SC)])
        reg = np.asarray(cv.crop((0, y0, W * T, y1)), dtype=np.float32).copy()
        out = fn(reg, ups, y0)
        cv.paste(Image.fromarray(np.clip(out, 0, 255).astype(np.uint8), "RGBA"), (0, y0))


TINT = {"salt": (1.0, 0.96, 0.88), "ash": (1.0, 0.9, 0.84), "rocky_deep": (0.78, 0.68, 0.62), "purple": (0.66, 0.6, 0.7), "grey": (0.85, 0.87, 0.9)}


def soft_fill(cv, mask, tile, W, H, seed, tint=None):
    """A ground kind laid over what is below with an organic, pixel-dithered edge."""
    lo = blur_low(cell_low(mask, W, H), LOW * 0.55) + smooth_noise(H, W, seed, 18) * 0.28 + smooth_noise(H, W, seed + 1, 3) * 0.16
    tex = np.asarray(tiled(tile, W * T, 11 * T), dtype=np.float32)
    if tint:
        tex[..., :3] *= np.array(tint, dtype=np.float32)

    def fn(reg, ups, y0):
        a = ups[0]
        on = a > 0.5
        reg[..., :3] = np.where(on[..., None], tex[:reg.shape[0], ..., :3], reg[..., :3])
        return reg
    strips(cv, W, H, [lo], fn)


def comp_major(grid, base0, W, H, kinds):
    """cell -> majority base ground of its connected patch (for each kind in kinds)."""
    out = {}
    seen = set()
    for y in range(H):
        for x in range(W):
            kk = grid[y][x]
            if kk not in kinds or (x, y) in seen:
                continue
            comp, st = [], [(x, y)]
            seen.add((x, y))
            while st:
                c = st.pop()
                comp.append(c)
                for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                    n = (c[0] + dx, c[1] + dy)
                    if 0 <= n[0] < W and 0 <= n[1] < H and n not in seen and grid[n[1]][n[0]] == kk:
                        seen.add(n)
                        st.append(n)
            cnt = {}
            for c in comp:
                cnt[base0[c[1]][c[0]]] = cnt.get(base0[c[1]][c[0]], 0) + 1
            if len(comp) > 150:
                # big ranges: majority per 12x12 block so a long ridge can change look along its length
                blk = {}
                for c in comp:
                    blk.setdefault((c[0] // 12, c[1] // 12), {}).setdefault(base0[c[1]][c[0]], 0)
                    blk[(c[0] // 12, c[1] // 12)][base0[c[1]][c[0]]] += 1
                for c in comp:
                    d = blk[(c[0] // 12, c[1] // 12)]
                    out[c] = max(d, key=d.get)
            else:
                m = max(cnt, key=cnt.get)
                for c in comp:
                    out[c] = m
    return out


def liquid(cv, mask, tile, W, H, seed, foam, shallow, bank, deep_mask=None, deep_tile=None):
    lo = blur_low(cell_low(mask, W, H), LOW * 0.42) + smooth_noise(H, W, seed, 14) * 0.16
    bk = blur_low((lo > 0.5).astype(np.float32), 2.0)
    lows = [lo, bk]
    if deep_mask is not None:
        lows.append(blur_low(cell_low(deep_mask, W, H), LOW * 0.9))
    di = 2
    tex = np.asarray(tiled(tile, W * T, 11 * T), dtype=np.float32)
    dtex = np.asarray(tiled(deep_tile, W * T, 11 * T), dtype=np.float32) if deep_tile is not None else None
    fo = np.array(foam, dtype=np.float32)

    def fn(reg, ups, y0):
        a = ups[0]
        h = reg.shape[0]
        t = tex[:h]
        rgb = reg[..., :3]
        water = a > 0.5
        rgb[(ups[1] > 0.12) & ~water] *= bank
        w = t[..., :3].copy()
        if dtex is not None:
            dm = np.clip((ups[2] - 0.35) / 0.3, 0, 1)[..., None]
            w = w * (1 - dm) + (w * 0.58 + np.array([6, 20, 52], dtype=np.float32)) * dm
        sh = ((a > 0.5) & (a < 0.72))[..., None]
        w = np.where(sh, w * shallow + np.array([6, 14, 14], dtype=np.float32) * (shallow > 1), w)
        f = ((a > 0.5) & (a < 0.555))[..., None]
        w = np.where(f, w * 0.35 + fo * 0.65, w)
        rgb[:] = np.where(water[..., None], w, rgb)
        return reg
    strips(cv, W, H, lows, fn)


def thin(cells):
    """Drop cells of 2x2 road blocks where the network stays connected (visual only: fewer little rings)."""
    cells = set(cells)
    ring = [(-1, -1), (0, -1), (1, -1), (1, 0), (1, 1), (0, 1), (-1, 1), (-1, 0)]
    changed = True
    while changed:
        changed = False
        for c in sorted(cells):
            x, y = c
            if not any(all((x + a, y + b) in cells for a, b in blk) for blk in
                       (((0, 0), (1, 0), (0, 1), (1, 1)), ((0, 0), (-1, 0), (0, 1), (-1, 1)),
                        ((0, 0), (1, 0), (0, -1), (1, -1)), ((0, 0), (-1, 0), (0, -1), (-1, -1)))):
                continue
            four = [(dx, dy) for dx, dy in ((0, -1), (1, 0), (0, 1), (-1, 0)) if (x + dx, y + dy) in cells]
            if len(four) < 2:
                continue
            cs = {(dx, dy) for dx, dy in ring if (x + dx, y + dy) in cells}
            comp, st = {four[0]}, [four[0]]
            while st:
                a = st.pop()
                for b in cs:
                    if b not in comp and abs(a[0] - b[0]) + abs(a[1] - b[1]) == 1:
                        comp.add(b)
                        st.append(b)
            if all(f in comp for f in four):
                cells.discard(c)
                changed = True
    return cells


def chains(cells):
    """Split a 4-connected cell network into chains between junctions/ends (ordered cell lists)."""
    nb = lambda c: [(c[0] + dx, c[1] + dy) for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)) if (c[0] + dx, c[1] + dy) in cells]
    deg = {c: len(nb(c)) for c in cells}
    seen_e = set()
    out = []
    for c in sorted(cells):
        if deg[c] == 2:
            continue
        for n in nb(c):
            if (c, n) in seen_e:
                continue
            ch = [c, n]
            seen_e.add((c, n)); seen_e.add((n, c))
            prev, cur = c, n
            while deg[cur] == 2:
                nx = [m for m in nb(cur) if m != prev][0]
                seen_e.add((cur, nx)); seen_e.add((nx, cur))
                ch.append(nx)
                prev, cur = cur, nx
                if cur == c:
                    break
            out.append(ch)
    for c in sorted(cells):   # pure loops
        if deg[c] == 2 and not any((c, n) in seen_e for n in nb(c)):
            ch, prev, cur = [c], None, c
            while True:
                nx = [m for m in nb(cur) if m != prev and (cur, m) not in seen_e]
                if not nx:
                    break
                seen_e.add((cur, nx[0])); seen_e.add((nx[0], cur))
                ch.append(nx[0]); prev, cur = cur, nx[0]
            out.append(ch)
    return out, deg


def smooth_pts(pts):
    if len(pts) > 3:
        pts = [pts[0]] + pts[1:-1:2] + [pts[-1]]
    for _ in range(3):
        if len(pts) < 3:
            break
        q = [pts[0]]
        for a, b in zip(pts, pts[1:]):
            q.append((a[0] * 0.75 + b[0] * 0.25, a[1] * 0.75 + b[1] * 0.25))
            q.append((a[0] * 0.25 + b[0] * 0.75, a[1] * 0.25 + b[1] * 0.75))
        q.append(pts[-1])
        pts = q
    return pts


def _mask_lines(W, H, cells, width):
    """Road ribbon mask at low res: each chain between junctions drawn as a smoothed polyline."""
    s = LOW
    m = Image.new("L", (W * s, H * s), 0)
    d = ImageDraw.Draw(m)
    ww = max(2, int(round(width / SC)))
    chs, deg = chains(cells)
    for ch in chs:
        pts = smooth_pts([(x * s + s / 2, y * s + s / 2) for x, y in ch])
        d.line(pts, fill=255, width=ww, joint="curve")
        for p in (pts[0], pts[-1]):
            d.ellipse((p[0] - ww / 2, p[1] - ww / 2, p[0] + ww / 2, p[1] + ww / 2), fill=255)
    for c, dg in deg.items():
        if dg == 0:
            cx, cy = c[0] * s + s / 2, c[1] * s + s / 2
            d.ellipse((cx - ww / 2, cy - ww / 2, cx + ww / 2, cy + ww / 2), fill=255)
    return m.filter(ImageFilter.GaussianBlur(1.2))


def bridge_masks(grid, W, H):
    """Bridge cells split by the way they are walked: (horizontal-walk mask, vertical-walk mask)."""
    br = {(x, y) for y in range(H) for x in range(W) if grid[y][x] == "bridge"}
    mh = np.zeros((H, W), bool)
    mv = np.zeros((H, W), bool)
    seen = set()
    for c in sorted(br):
        if c in seen:
            continue
        comp, st = [], [c]
        seen.add(c)
        while st:
            a = st.pop()
            comp.append(a)
            for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                n = (a[0] + dx, a[1] + dy)
                if n in br and n not in seen:
                    seen.add(n)
                    st.append(n)
        xs = [q[0] for q in comp]
        ys = [q[1] for q in comp]
        if max(xs) - min(xs) != max(ys) - min(ys):
            horiz = max(xs) - min(xs) > max(ys) - min(ys)
        else:
            land = lambda x, y: 0 <= x < W and 0 <= y < H and grid[y][x] not in SEA + ("bridge",)
            horiz = sum(land(q[0] - 1, q[1]) + land(q[0] + 1, q[1]) for q in comp) >= \
                sum(land(q[0], q[1] - 1) + land(q[0], q[1] + 1) for q in comp)
        for q in comp:
            (mh if horiz else mv)[q[1], q[0]] = True
    return mh, mv


def roads(cv, grid, W, H, deep):
    rd = {(x, y) for y in range(H) for x in range(W) if grid[y][x] in ("road",)}
    pa = {(x, y) for y in range(H) for x in range(W) if grid[y][x] in ("path",)}
    br = {(x, y) for y in range(H) for x in range(W) if grid[y][x] == "bridge"}
    for c in br:   # bridges join whichever network touches them
        (rd if any((c[0] + dx, c[1] + dy) in rd for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1))) else pa).add(c)
    mh, mv = bridge_masks(grid, W, H)
    bh = blur_low(cell_low(mh, W, H), 2.0)
    bv = blur_low(cell_low(mv, W, H), 2.0)
    src = SHEETS["B"].crop((6 * T + 18, 1 * T + 28, 6 * T + 78, 1 * T + 38))
    ph = np.asarray(tiled(src, W * T, 11 * T), dtype=np.float32)
    pv = np.asarray(tiled(src.rotate(90, expand=True), W * T, 11 * T), dtype=np.float32)
    rail = np.array([58, 38, 30], dtype=np.float32)
    for cells, width, tex, seed in ((pa, 20, GROUND["dirt"], 3), (rd, 30, GROUND["cobble"] if deep else GROUND["dirt"], 4)):
        if not cells:
            continue
        m = np.asarray(_mask_lines(W, H, thin(cells), width), dtype=np.float32) / 255.0
        mn = m + smooth_noise(H, W, seed, 8) * 0.30
        ft = np.asarray(tiled(interior(tex), W * T, 11 * T), dtype=np.float32)
        worn = cells is rd and not deep

        def fn(reg, ups, y0):
            a, clean, uh, uv = ups
            h = reg.shape[0]
            rgb = reg[..., :3]
            core = a > 0.5
            rim = (a > 0.40) & ~core
            f = ft[:h, ..., :3].copy()
            if worn:
                f = np.where((a > 0.9)[..., None], f * 1.08, f)
            rgb[:] = np.where(core[..., None], f, rgb)
            rgb[rim] *= 0.78
            # bridges: planks across the water with dark rails (clean edges, no wear noise)
            on_h = (uh > 0.5)
            on_v = (uv > 0.5) & ~on_h
            deck = clean > 0.5
            rgb[:] = np.where((deck & on_h)[..., None], ph[:h, ..., :3], rgb)
            rgb[:] = np.where((deck & on_v)[..., None], pv[:h, ..., :3], rgb)
            rl = (clean > 0.28) & ~deck & (on_h | on_v)
            rgb[rl] = rail
            return reg
        strips(cv, W, H, [mn, m, bh, bv], fn)


def bridges(cv, grid, W, H):
    B = SHEETS["B"]
    wood_h = B.crop((6 * T, 1 * T, 8 * T, 2 * T))
    wood_h = wood_h.crop(wood_h.getbbox())
    mid_h = wood_h.crop((wood_h.width // 2 - 12, 0, wood_h.width // 2 + 12, wood_h.height))
    for y in range(H):
        for x in range(W):
            if grid[y][x] != "bridge":
                continue
            horiz = (x > 0 and grid[y][x - 1] not in SEA) or (x < W - 1 and grid[y][x + 1] not in SEA) or \
                    (x > 0 and grid[y][x - 1] == "bridge") or (x < W - 1 and grid[y][x + 1] == "bridge")
            vert = (y > 0 and grid[y - 1][x] in ("bridge",) + tuple(k for k in ("road", "path"))) or \
                   (y < H - 1 and grid[y + 1][x] in ("bridge", "road", "path"))
            if vert and not ((x > 0 and grid[y][x - 1] in ("bridge", "road", "path")) or (x < W - 1 and grid[y][x + 1] in ("bridge", "road", "path"))):
                horiz = False
            tile = Image.new("RGBA", (T, mid_h.height))
            tile.paste(mid_h, (0, 0))
            tile.paste(mid_h, (24, 0))
            if horiz:
                cv.alpha_composite(tile, (x * T, y * T + (T - tile.height) // 2))
            else:
                t2 = tile.rotate(90, expand=True)
                cv.alpha_composite(t2, (x * T + (T - t2.width) // 2, y * T))


def mountains(cv, grid, cb, W, H, deep, rng):
    MT = SHEETS["M"]
    solid = "wall_rock" if deep else "mountain"
    for y in range(H):
        for x in range(W):
            if grid[y][x] != solid:
                continue
            if deep:
                # only the rock face near open floor gets peaks; deep rock stays dark mass
                near = any(0 <= x + dx < W and 0 <= y + dy < H and grid[y + dy][x + dx] != "wall_rock"
                           for dx in (-2, -1, 0, 1, 2) for dy in (-2, -1, 0, 1, 2))
                if not near:
                    continue
            b = cb.get((x, y), "plains")
            fam = PEAK_BY_BASE.get(b, "green")
            c, r = rng.choice(PEAKS[fam])
            spr = MT.crop((c * T, r * T, c * T + 96, r * T + 96))
            if deep:
                spr = Image.eval(spr, lambda v: v)  # keep
                arr = np.asarray(spr, dtype=np.float32)
                arr[..., :3] *= 0.55
                spr = Image.fromarray(arr.astype(np.uint8), "RGBA")
            cv.alpha_composite(spr, (x * T - 24 + rng.randint(-5, 5), y * T - 44 + rng.randint(-3, 3)))


def deep_rock(cv, grid, W, H):
    """Solid rock far from any floor: near-black with faint texture, under the peaks pass."""
    pass


# ---------------------------------------------------------------- objects
def places_for(mid):
    if mid == "WORLD":
        return wgen.PLACES, {}
    if mid == "WORLD_POST":
        return wgen.PLACES_POST, {k: wgen.PLACES[k] for k in wgen.DESTROYED}
    return wgen.DEEP_PLACES, {}


def objects(sec, atlas, W, H):
    mid = sec["id"]
    grid = sec["grid"]
    places, destroyed = places_for(mid)
    objs = []
    taken = set()
    for pid, v in list(places.items()) + [(k, v) for k, v in destroyed.items()]:
        x, y, kind, reg = v
        if pid in destroyed:
            kind = "destroyed"
        name = FIXED.get(pid) if pid not in destroyed else None
        if not name:
            opts = KIND.get("%s@%s" % (kind, reg)) or KIND.get(kind) or ["obelisk"]
            name = pick(opts, pid)
        atlas.get(name)
        objs.append([name, x, y, pid])
        taken.add((x, y))
    # signposts at road forks, lamps (milestones) along long roads
    rd = {(x, y) for y in range(H) for x in range(W) if grid[y][x] in ("road", "path")}
    signs = []

    def far(c, lst, dmin):
        return all(abs(c[0] - o[0]) + abs(c[1] - o[1]) >= dmin for o in lst)
    for (x, y) in sorted(rd):
        n = sum((x + dx, y + dy) in rd for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)))
        if n >= 3 and far((x, y), taken, 4) and far((x, y), signs, 6):
            # the post stands beside the road, not on it
            for dx, dy in ((1, 1), (-1, 1), (1, -1), (-1, -1), (1, 0), (-1, 0)):
                c = (x + dx, y + dy)
                if 0 <= c[0] < W and 0 <= c[1] < H and c not in rd and grid[c[1]][c[0]] in BASEK:
                    signs.append(c)
                    objs.append(["sign", c[0], c[1], ""])
                    break
    lamps = []
    step = 0
    for (x, y) in sorted(rd, key=lambda c: (c[1] // 12, c[0])):
        step += 1
        if step % 17 == 0 and far((x, y), taken, 5) and far((x, y), signs + lamps, 9):
            for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                c = (x + dx, y + dy)
                if 0 <= c[0] < W and 0 <= c[1] < H and c not in rd and grid[c[1]][c[0]] in BASEK:
                    lamps.append(c)
                    objs.append(["lamp", c[0], c[1], ""])
                    break
    atlas.get("sign")
    atlas.get("lamp")
    return objs


def write(mid, cv, W, H, objs, pos, atlas_name, preview):
    os.makedirs(OUT, exist_ok=True)
    chunks = []
    for cy in range(0, H * T, CHUNK):
        for cx in range(0, W * T, CHUNK):
            w, h = min(CHUNK, W * T - cx), min(CHUNK, H * T - cy)
            fn = "%s_g%d_%d.png" % (mid, cx // CHUNK, cy // CHUNK)
            cv.crop((cx, cy, cx + w, cy + h)).convert("RGB").save(os.path.join(OUT, fn), optimize=True)
            chunks.append([fn, cx, cy, w, h])
    ob = []
    for name, x, y, pid in objs:
        sx, sy, sw, sh, nf = pos[name]
        px = x * T + T // 2 - sw // 2
        base = (y + 1) * T - 2
        ob.append([0, sx, sy, sw, sh, px, base - sh, base, nf, pid])
    ob.sort(key=lambda o: o[7])
    data = {"id": mid, "w": W, "h": H, "ground": "", "chunks": chunks, "over": "", "sheets": ["maps48/" + atlas_name],
            "objects": ob, "anims": [], "mode7": True}
    json.dump(data, open(os.path.join(OUT, mid + ".json"), "w"))
    if preview:
        pv = cv.copy()
        at = Image.open(os.path.join(OUT, atlas_name))
        for o in ob:
            pv.alpha_composite(at.crop((o[1], o[2], o[1] + o[3], o[2] + o[4])), (o[5], o[6]))
        pv.convert("RGB").save(os.path.join(OUT, "..", mid + "_preview.png"))
    print(mid, "chunks", len(chunks), "objects", len(ob))


MINI = 3   # minimap: native px per map cell


def write_meta(mid):
    """Minimap image (3 px per cell, from the baked chunks) and the named place list for the map screens."""
    jp = os.path.join(OUT, mid + ".json")
    data = json.load(open(jp))
    W, H = data["w"], data["h"]
    mini = Image.new("RGB", (W * MINI, H * MINI))
    for fn, cx, cy, w, h in data["chunks"]:
        im = Image.open(os.path.join(OUT, fn)).convert("RGB")
        im = im.resize((w * MINI // T, h * MINI // T), Image.BOX)
        mini.paste(im, (cx * MINI // T, cy * MINI // T))
    mini.save(os.path.join(OUT, mid + "_mini.png"), optimize=True)
    places, destroyed = places_for(mid)
    data["mini"] = mid + "_mini.png"
    data["mini_scale"] = MINI
    data["places"] = [[pid, wgen.PLACE_NAMES.get(pid[2:], pid[2:]), v[0], v[1], v[2]] for pid, v in sorted(places.items())]
    json.dump(data, open(jp, "w"))
    print(mid, "meta", len(data["places"]), "places")


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    mids = args or ["WORLD", "WORLD_POST", "DEEP", "DEEP_POST"]
    if "--meta" in sys.argv:
        for mid in mids:
            write_meta(mid)
        return
    secs = sections()
    atlas = Atlas()
    for name in sorted(S):   # every sprite, always in the same order: a partial bake keeps the others' coordinates
        atlas.get(name)
    baked = []
    for mid in mids:
        sec = secs[mid]
        deep = mid.startswith("DEEP")
        cv, W, H = bake(sec, mid == "WORLD_POST" or mid == "DEEP_POST", deep)
        objs = objects(sec, atlas, W, H)
        baked.append((mid, cv, W, H, objs))
    im, pos = atlas.pack()
    os.makedirs(OUT, exist_ok=True)
    im.save(os.path.join(OUT, "world2_bill.png"))
    for mid, cv, W, H, objs in baked:
        write(mid, cv, W, H, objs, pos, "world2_bill.png", "--preview" in sys.argv)
        write_meta(mid)


if __name__ == "__main__":
    main()
