"""Group e: the second half of the Deep, U20-U40 (all post-fault).
U2 the Lattice (U20-U27) and U3 the Hollow Throne (U28-U40). Maps: content_src/maps/x_e.map;
scenes: content_src/scenes/x_e.scn."""

SHOPS = {
    "SHOP_U26": {"name": "Terminus Kiosk", "kinds": ["items"], "town": "U26"},
    "SHOP_U29": {"name": "Wreath & Lamp", "kinds": ["items", "weapons", "armor", "accessories"], "town": "U29"},
    "SHOP_U34": {"name": "Pilgrims' Sutler", "kinds": ["items", "armor"], "town": "U34"},
    "SHOP_U37": {"name": "Weeping Mines Smithy", "kinds": ["items", "weapons", "armor"], "town": "U37"},
}

SPEAKERS = {
    # U2 the Lattice
    "ines": ["Ines", "clerk"], "dov": ["Dov", "apprentice"], "index": ["The Index", ""],
    "oona": ["Oona", "sailor"], "hesk": ["Hesk", "keeper"], "thrale": ["Thrale", "elder"],
    "brin": ["Brin", "worker"], "pellansa": ["Pell-Ansa", "clerk"], "tollunit": ["Toll Unit", ""],
    "dispatch": ["Dispatch", ""], "maint": ["Maintenance Unit", ""], "kael00": ["Kael-00", ""],
    "anwe": ["Anwe", "keeper"], "curator": ["CURATOR", ""], "lamplighter": ["Lamplighter", "keeper"],
    "mave": ["Mave", "worker"], "coyle": ["Coyle", "elder"], "groundskeeper": ["Groundskeeper", ""],
    "sael": ["Sael", "survivor"],
    # U3 the Hollow Throne
    "oarsman": ["The Oarsman", "elder"], "tollclerk": ["Toll Clerk", "clerk"],
    "osric": ["Osric", "guard"], "mab": ["Mab", "baker"], "candlewright": ["Candle-Wright", "keeper"],
    "crier": ["Roll-Crier", "clerk"], "aveline": ["Aveline Marsh", "guard"], "hedd": ["Hedd", "worker"],
    "ysolt": ["Dame Ysolt", "elder"], "coll": ["Coll", "worker"], "pim": ["Pim", "child"],
    "gwyl": ["Gwyl", "elder"], "tallow": ["Tallow", "keeper"], "idris": ["Idris", "worker"],
    "registrar": ["The Registrar", "clerk"], "fenn": ["Fenn", "clerk"], "aldous": ["Master Aldous", "elder"],
    "aldousf": ["Mistress Aldous", "elder"], "tobin": ["Tobin", "child"], "harl": ["Harl", "worker"],
    "wenna": ["Wenna", "survivor"], "rusk": ["Rusk", "guard"], "nell": ["Nell Tanner", "survivor"],
    "aud": ["Aud", "clerk"], "brona": ["Brona", "baker"], "pry": ["Pry", "keeper"], "jossa": ["Jossa", "apprentice"],
    "orla": ["Orla", "elder"], "garrow": ["Old Garrow", "worker"], "quist": ["Quist", "clerk"],
    "ada": ["Ada", "survivor"], "hesper": ["Hesper", "baker"], "tarn": ["Tarn", "worker"],
    "dilly": ["Dilly", "apprentice"], "brack": ["Foreman Brack", "elder"], "pewwarden": ["Pew-Warden", "keeper"],
    "lockkeeper": ["Lock-Keeper", "sailor"], "sef": ["Sef", "survivor"], "netter": ["Soul-Netter", "elder"],
    "dunstan": ["Dunstan", "elder"], "bridgewright": ["Bridgewright", "worker"], "ossuan": ["Ossuan", ""],
    "doorwarden": ["Doorwarden", "guard"], "sepulchre": ["Mother Sepulchre", ""], "adopted": ["The Adopted", "survivor"],
    "warden_debts": ["The Warden of Debts", ""], "carrier": ["Carrier", "guard"],
    "firstcrown": ["The First Crown", ""], "mourningcourt": ["The Mourning Court", ""],
    "courtier": ["Lady Esk", "elder"], "page": ["Page", "child"], "sorrow": ["Sorrow", "survivor"],
    "lastpilgrim": ["The Last Pilgrim", "elder"],
    "noble": ["Mourner", "elder"], "farmer": ["Farmer", "worker"], "soldier": ["Soldier", "guard"],
}

_NAMES = {
    "U20": "The Datum Archive", "U21": "Glasswater Reservoir", "U22": "The Highway That Was", "U23": "Vault Omega",
    "U24": "Prime Relay", "U25": "Shutdown Town", "U26": "Mag-rail Terminus", "U27": "The Sunless Garden",
    "U28": "Styx Landing", "U29": "Cenotaph", "U30": "The Bone Bridges", "U31": "Sepulchre Court",
    "U32": "Abyss Gate", "U33": "The First Crown's Tomb", "U34": "Mourner's Vale", "U35": "The Lich Stair",
    "U36": "Velkhar's Crypt-Gate", "U37": "Weeping Mines", "U38": "The Silent Choir", "U39": "Hollow Heart",
    "U40": "Undersea Throat",
}
LOCATIONS = {"L_" + k: {"name": v, "map": k + "_R01", "spawn": "world"} for k, v in _NAMES.items()}

QUESTS = [
    {"id": "QBM1", "name": "The Datum Archive", "start": "U20", "location": "U20", "character": None,
     "hook": "Archivist Ines asks the party to save the Datum Archive's master index before the Index deletes it",
     "objectives": "Recover three datum cores (the Stacks, the Deletion Floor, the Index Gallery); defeat the Index; restore the master index at its terminal",
     "decision": "Restore everything, including the Crown's records of how it copied the Prime Relay, or restore it with the relay design deleted so nobody copies CURATOR again",
     "result": "The archive is restored; its index points to the Prime Relay (starts QBM3); the Lanternwake can take Gale Vanes (flag gale_vanes)",
     "reward": "Gale Vanes (flag), Reserve Cell A016, 3000 crowns", "boss": "BX19"},
    {"id": "QBM2", "name": "Shutdown Town", "start": "U25", "location": "U25", "character": None,
     "hook": "The Lamplighter, the one machine left awake in Shutdown Town, cannot decide how the town should answer CURATOR's call",
     "objectives": "Read the three citizens' door plates; decide at the Mayor's switch",
     "decision": "Leave all four thousand switched off, or rewire the switch so each citizen can choose (eleven wake)",
     "result": "Shutdown Town answers CURATOR in its own time", "reward": "Mercy Thread A020", "boss": None},
    {"id": "QBM3", "name": "CURATOR", "start": "U20", "location": "U24", "character": None,
     "hook": "The restored Datum Archive (or the Prime Relay's own Signal Gate) shows that CURATOR, the builder mind, is awake",
     "objectives": "Wake the three sub-nodes of the Listening Galleries; see the Copy Room; speak with CURATOR at the Inner Seal",
     "decision": "Tell CURATOR the builders are gone, or say nothing and let it sleep",
     "result": "CURATOR stays behind the seal (flags curator_spoken, qbm3_told / qbm3_silent); its superboss tier is reached later",
     "reward": "4000 crowns", "boss": None},
    {"id": "QC16", "name": "Standing Orders", "start": "U17", "location": "U24", "character": "C16",
     "hook": "After Meridian (flag qc16_meridian_done), Kael-09 returns to Vault Omega looking for Kael-00, the prototype",
     "objectives": "Enter Vault Omega; read the Hall of Standing Orders; defeat Kael-00 in the Prototype Bay; take Kael-09 to the Prime Relay's Inner Seal",
     "decision": "The party relieves Kael-09 of duty themselves, or makes CURATOR say it",
     "result": "Kael-09 is relieved and chooses his own orders", "reward": "True Name W047", "boss": "BX20"},
    {"id": "QC17", "name": "The Highway That Was", "start": "P02", "location": "U22", "character": "C17",
     "hook": "After the surface half at the Tessellate (flag qc17_surface_done), the Night Rider finds his old patrol road in the Lattice",
     "objectives": "Relight the three road lamps of Route Nine; hear the dispatcher's last call at the Last Toll; ride to the edge of the road",
     "decision": "Take the last call and go off duty, or log a new patrol of the roads the living use",
     "result": "The Night Rider finds a road worth riding now", "reward": "Common Engine W023", "boss": None},
    {"id": "QUP4", "name": "Cenotaph", "start": "U34", "location": "U29", "character": None,
     "hook": "Wenna, a living pilgrim at Mourner's Vale, lost her son Tobin on the barge across the black lake",
     "objectives": "Find Tobin in Cenotaph's Aldous house; ask the Registrar; get the Oarsman's fare page at Styx Landing; return to the Registrar; see Tobin home",
     "decision": "Strike Tobin's name at once, or let the dead Aldous couple (who lost their own son) walk him to the boat",
     "result": "Tobin goes home to Wenna; the Honour Roll has one blank page", "reward": "Salt Locket A013, Elixir I024", "boss": None},
    {"id": "QC11", "name": "Ledger of the Damned", "start": "U28", "location": "U32", "character": "C11",
     "hook": "At Styx Landing the Oarsman calls three names Inferna once carried down as debts",
     "objectives": "Hear the three debts (Aveline Marsh in Cenotaph, Hobb Tanner's daughter at Mourner's Vale, Old Garrow at the Weeping Mines); defeat the Warden of Debts at the Abyss Gate",
     "decision": "Burn the whole Great Ledger, or strike the debts one name at a time",
     "result": "Inferna keeps her own page and resolves to pay it by carrying people out", "reward": "Returner's Pike W017", "boss": "BX23"},
    {"id": "QC13", "name": "A Court Too Long in Mourning", "start": "N35", "location": "U35", "character": "C13",
     "hook": "After Coldharbour (flag qc13_citadel_done) the Lich King descends to his under-court",
     "objectives": "Descend the Lich Stair; relight the Frozen Court's braziers; defeat the Mourning Court; release the court",
     "decision": "Lay his crown on the under-throne now, or carry it until the Ashen Crown is broken",
     "result": "The Lich King releases the dead he kept", "reward": "Dawn Conductor W011", "boss": "BX25"},
    {"id": "QC14", "name": "The First Crown", "start": "N05", "location": "U33", "character": "C14",
     "hook": "After the Ashward Barrows beat (stage barrows), Maldrath goes down to the First Crown's Tomb",
     "objectives": "Enter the tomb; read his own plaque on the Processional of Kings; defeat the First Crown",
     "decision": "Break the original crown, or bury it with its king as nobody's",
     "result": "Maldrath answers for the crown he wore and turns to the one that remains", "reward": "Accord Steel W005", "boss": "BX24"},
    {"id": "QC15", "name": "The Teacher Below", "start": "U36", "location": "U31", "character": "C15",
     "hook": "Velkhar returns to the Crypt-Gate where his first student Sorrow stayed to hold it",
     "objectives": "Descend the Crypt-Gate; face Sorrow; learn that Mother Sepulchre adopted the dead he laid to rest; defeat her at Sepulchre Court",
     "decision": "Command the adopted dead to rest (as she taught him), or ask each of them what they want",
     "result": "The adopted dead are freed; Velkhar keeps the living from needing him", "reward": "Prism Focus G030", "boss": "BX22"},
]
