"""Deterministic programmatic art build. Writes game/assets/** and reports/asset_ledger.json.

All assets are original, generated by code in tools/art (generator version in art/pix.py).
Status labels: 'generated' (programmatic, self-reviewed only). Nothing here is claimed as final art.
"""
import hashlib, json, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from PIL import Image
from art.pix import GEN_VERSION, LICENSES, pack_of, lib_available
from art import figures, world_sprites, tiles

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
A = os.path.join(ROOT, "game", "assets")
ledger = []


def save(img, rel, kind, frames="", palette="", note=""):
    path = os.path.join(A, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    img.save(path)
    h = hashlib.sha256(open(path, "rb").read()).hexdigest()[:12]
    ledger.append({"path": "game/assets/" + rel, "w": img.width, "h": img.height, "kind": kind, "frames": frames,
                   "palette": palette, "source": f"tools/gen_art.py ({GEN_VERSION})", "license": "original (project-generated)",
                   "status": "generated", "sha": h, "note": note})


def save_ext(img, rel, kind, sources, frames="", note=""):
    """Library-derived asset -> game/assets/ext/<rel> (git-ignored). `sources`: library-relative source paths."""
    path = os.path.join(A, "ext", rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    if isinstance(img, (dict, list)):
        json.dump(img, open(path, "w"), indent=1)
    else:
        img.save(path)
    h = hashlib.sha256(open(path, "rb").read()).hexdigest()[:12]
    packs = sorted({pack_of(s) for s in sources})
    ledger.append({"path": "game/assets/ext/" + rel, "w": getattr(img, "width", 0), "h": getattr(img, "height", 0),
                   "kind": kind, "frames": frames, "palette": "", "source": "; ".join(sorted(set(sources))),
                   "license": " | ".join(LICENSES.get(p, p + " (licence not recorded)") for p in packs),
                   "status": "library", "sha": h, "note": note})


def build_library(only=None):
    """Assemble ext/ assets from the owner's library. Each tools/art module may define build_library(save_ext)."""
    if not lib_available():
        print("library not found (set ASHEN_LIB); ext/ left unchanged")
        return
    for mod in only or ["tiles", "world_sprites", "battle", "portraits", "enemies", "bgs", "ui"]:
        m = __import__(f"art.{mod}", fromlist=["x"])
        if hasattr(m, "build_library"):
            m.build_library(save_ext)


def build(only=None):
    todo = only or ["world", "tiles", "battle", "portraits", "enemies", "bgs", "ui", "creatures"]
    if todo and todo[0] == "library":
        build_library(todo[1:] or None)
        todo = []
    if "world" in todo:
        for cid, f in list(figures.FIG.items()) + list(figures.NPCS.items()):
            save(world_sprites.sheet(f), f"sprites/world/{cid}.png", "world_sprite",
                 "24x32; rows down,left,right,up x5 (idle+4 walk); row4 six poses")
    if "tiles" in todo:
        for name in tiles.P:
            atlas, props = tiles.build_tileset(name)
            save(atlas, f"tiles/{name}.png", "tileset", f"16x16; {len(tiles.KINDS)} kinds x 4 variants", name)
            save(props, f"tiles/{name}_props.png", "props", f"16x32 x {len(tiles.PROPS)}", name)
        with open(os.path.join(A, "tiles", "kinds.json"), "w") as f:
            json.dump({"kinds": tiles.KINDS, "props": tiles.PROPS}, f)
    for mod in ["battle", "portraits", "enemies", "bgs", "ui", "creatures"]:
        if mod in todo:
            try:
                m = __import__(f"art.{mod}", fromlist=["build"])
            except ModuleNotFoundError:
                continue
            m.build(save)
    os.makedirs(os.path.join(ROOT, "reports"), exist_ok=True)
    lp = os.path.join(ROOT, "reports", "asset_ledger.json")
    old = []
    if os.path.exists(lp):
        new = {x["path"] for x in ledger}
        keep_all = bool(only) or not todo          # partial or library-only runs keep everything else
        old = [e for e in json.load(open(lp)) if e["path"] not in new and (keep_all or e["status"] == "library")]
    json.dump(sorted(old + ledger, key=lambda e: e["path"]), open(lp, "w"), indent=1)
    print("assets:", len(ledger), "ledger total:", len(old) + len(ledger))


if __name__ == "__main__":
    build(sys.argv[1:] or None)
